---
komga:
  path: '/opt/komga'
  user:
    name: 'komga'
  group:
    name: 'komga'
  port: '25600'
  internal_data_path: '/path/to/my/komga/data/folder'
  ebooks_path: '/path/to/my/ebooks/data/folder'
  comics_path: '/path/to/my/comics/data/folder'
  maintenance:
    start_time:
      cron_hour: 3
      cron_minute: 0
    end_time:
      cron_hour: 5
      cron_minute: 0
  update_docker:
    time:
      cron_hour: 4
      cron_minute: 30
  backup:
    time:
      cron_hour: 3
      cron_minute: 5
    rsync_target: 'backup_user@rsync_server::backup_target'
