---
- name: Create installation directory
  ansible.builtin.file:
    path: '{{ komga.path }}'
    state: directory
    owner: '{{ komga.user.name }}'
    group: '{{ komga.group.name }}'
    mode: '0775'
- name: Create data directory
  ansible.builtin.file:
    path: '{{ komga.internal_data_path }}'
    state: directory
    owner: '{{ komga.user.name }}'
    group: '{{ komga.group.name }}'
    mode: '0770'
- name: Get komga user info
  ansible.builtin.getent:
    database: passwd
    key: '{{ komga.user.name }}'
- name: Copy docker-compose.yml
  ansible.builtin.template:
    src: docker-compose.yml.j2
    dest: '{{ komga.path }}/docker-compose.yml'
    owner: root
    group: root
    mode: '0664'
  vars:
    uid: '{{ ansible_facts.getent_passwd[komga.user.name][1] }}'
    gid: '{{ ansible_facts.getent_passwd[komga.group.name][1] }}'
- name: Enable daily service shutdown for maintenance
  ansible.builtin.cron:
    name: 'Start Maintenance {{ komga.path }}'
    user: root
    hour: '{{ komga.maintenance.start_time.cron_hour }}'
    minute: '{{ komga.maintenance.start_time.cron_minute }}'
    job: 'docker compose -f {{ komga.path }}/docker-compose.yml down'
- name: Enable daily upgrade of base image
  ansible.builtin.cron:
    name: 'Upgrade {{ komga.path }}'
    user: root
    hour: '{{ komga.update_docker.time.cron_hour }}'
    minute: '{{ komga.update_docker.time.cron_minute }}'
    job: 'docker compose -f {{ komga.path }}/docker-compose.yml pull'
- name: Enable daily service start from maintenance
  ansible.builtin.cron:
    name: 'End Maintenance {{ komga.path }}'
    user: root
    hour: '{{ komga.maintenance.end_time.cron_hour }}'
    minute: '{{ komga.maintenance.end_time.cron_minute }}'
    job: 'docker compose -f {{ komga.path }}/docker-compose.yml up -d'
- name: Copy scripts
  ansible.builtin.template:
    src: '{{ item }}.j2'
    dest: '{{ komga.path }}/{{ item }}'
    mode: '0755'
    owner: root
    group: root
  loop:
    - 'backup_komga.sh'
- name: Enable daily backup
  ansible.builtin.cron:
    name: 'Backup {{ komga.path }}'
    user: root
    hour: '{{ komga.backup.time.cron_hour }}'
    minute: '{{ komga.backup.time.cron_minute }}'
    job: '{{ komga.path }}/backup_komga.sh'
