---
- name: Create installation directory
  ansible.builtin.file:
    path: '{{ komga_path }}'
    state: directory
    owner: '{{ komga_user }}'
    group: '{{ komga_group }}'
    mode: '0775'
- name: Create data directory
  ansible.builtin.file:
    path: '{{ komga_data_path }}'
    state: directory
    owner: '{{ komga_user }}'
    group: '{{ komga_group }}'
    mode: '0770'
- name: Get komga user info
  ansible.builtin.getent:
    database: passwd
    key: '{{ komga_user }}'
- name: Copy docker-compose.yml
  ansible.builtin.template:
    src: docker-compose.yml.j2
    dest: '{{ komga_path }}/docker-compose.yml'
    owner: root
    group: root
    mode: '0664'
  vars:
    komga_user_id: '{{ ansible_facts.getent_passwd[komga_user][1] }}'
    komga_group_id: '{{ ansible_facts.getent_passwd[komga_group][1] }}'
- name: Enable daily service shutdown for maintenance
  ansible.builtin.cron:
    name: 'Start Maintenance {{ komga_path }}'
    user: root
    hour: '{{ komga.maintenance.start_time.cron_hour }}'
    minute: '{{ komga.maintenance.start_time.cron_minute }}'
    job: 'docker compose -f {{ komga_path }}/docker-compose.yml down'
- name: Enable daily upgrade of base image
  ansible.builtin.cron:
    name: 'Upgrade {{ komga_path }}'
    user: root
    hour: '{{ komga.update_time.cron_hour }}'
    minute: '{{ komga.update_time.cron_minute }}'
    job: 'docker compose -f {{ komga_path }}/docker-compose.yml pull'
- name: Enable daily service start from maintenance
  ansible.builtin.cron:
    name: 'End Maintenance {{ komga_path }}'
    user: root
    hour: '{{ komga.maintenance.end_time.cron_hour }}'
    minute: '{{ komga.maintenance.end_time.cron_minute }}'
    job: 'docker compose -f {{ komga_path }}/docker-compose.yml up -d'
- name: Copy scripts
  ansible.builtin.template:
    src: '{{ item }}.j2'
    dest: '{{ komga_path }}/{{ item }}'
    mode: '0755'
    owner: root
    group: root
  loop:
    - 'backup_komga.sh'
- name: Enable daily backup
  ansible.builtin.cron:
    name: 'Backup {{ komga_path }}'
    user: root
    hour: '{{ komga.backup_time.cron_hour }}'
    minute: '{{ komga.backup_time.cron_minute }}'
    job: '{{ komga_path }}/backup_komga.sh'
