---
komga:
  maintenance:
    start_time:
      cron_hour: 3
      cron_minute: 45
    end_time:
      cron_hour: 5
      cron_minute: 5
  update_time:
    cron_hour: 4
    cron_minute: 45
  backup_time:
    cron_hour: 1
    cron_minute: 0
